#!/usr/bin/python
#encoding=utf8
import difflib
#字符串1
text1 = """text1: This module provides classes and functions for comparing seqences. including HTml
and context and unified diffs and string
"""
#以行进行分隔，便于比较
text1_lines = text1.splitlines()
text2 = """text2: This module provodes classes and functions for Comoaring sequences.including HTMK
and context and unfied diffs
"""
text2_lines = text2.splitlines()
d = difflib.Differ() #创建differ对象
diff = d.compare(text1_lines, text2_lines)
print '\n'.join(list(diff))

======================================================================================================================
网页显示
#!/usr/bin/python#encoding=utf8import difflibtext1 = """text1: This module provides classes and functions for comparing seqences. including HTmland context and unified diffs and string"""text1_lines = text1.splitlines()text2 = """text2: This module provodes classes and functions for Comoaring sequences.including HTMKand context and unfied diffs"""text2_lines = text2.splitlines()d = difflib.HtmlDiff()print d.make_file(text1_lines, text2_lines)********************************************************************************************************python t.py > test.htmlURL 访问
#对比nginx配置文件差异

#!/usr/bin/python
#encoding=utf8
import difflib
import sys
try:
    t1=sys.argv[1] #得到配置文件路径
    t2=sys.argv[2]
except Exception,e: #错误输出
    print "ERROR:"+ str(e)
    print "Usage: t.py filename1 filename2"
    sys.exit()
def readfile(filename): #打开文件以行为分隔符读取
    try:
        fileHandle = open(filename,'rb')
        t = fileHandle.read().splitlines()
        fileHandle.close()
        return t
    except IOError as error: #文件不在的错误输出
        print ("Read File Error:" + str(error))
        sys.exit()
if t1=="" or t2=="": #输入错误
    print "Usage: t.py filename1 filename2"
    sys.exit()
t1_lines = readfile(t1)
t2_lines = readfile(t2)
d = difflib.HtmlDiff()
print d.make_file(t1_lines, t2_lines)
*****************************************************************************************************************************
python t.py t1.txt t2.txt > /var/www/html/text.html
URL访问
